### ISSUE TITLE
Crash on completing boss fight - 1.0.6-1

### ISSUE THREAD

**Issue by VIPT0xic** [waidesoper/thevaultstreamer#36]
[Server]
Entering a vault is fine, but when you complete the boss fight with the inscriptions the timer runs down to 0 before the server crashes

[SinglePlayer]
Game crashes on creation/joining of world.

Single Player World ---
[crash-2021-06-11_18.07.50-server.txt](https://github.com/waidesoper/thevaultstreamer/files/6640032/crash-2021-06-11_18.07.50-server.txt)

Server Crash Report ---
[crash-2021-06-11_18.02.51-server.txt](https://github.com/waidesoper/thevaultstreamer/files/6640031/crash-2021-06-11_18.02.51-server.txt)

**Comment by DDR-Khat** [comment]
Your crash in this regard is due to the new configuration file options being missing and not initialising a default.
go into ``.minecraft/config/the_vault/`` and find ``vault_coop_only.json``
It needs the extra entries that have been created since 1.0.6.
```{
  "IS_COOP_ONLY": false,
  "VAULT_EXP_EQUAL": false,
  "RAIDER_FRIENDLYFIRE": false,
  "EXTRA_BOSS_CRATES": false
}```
Above are the default values, and below is the explaination of them;
``IS_COOP_ONLY <true/false>`` This is used for enabling the co-op vaults. If this is enabled, anyone going into the vaults will need to join the hunters team by using the command ``/the_vault raider`` each time they wish to participate in a raid.

``VAULT_EXP_EQUAL <true/false>`` This makes it that everyone gets an equal amount of EXP when the vault is over on "true", otherwise each player gets a randomised amount.

``RAIDER_FRIENDLYFIRE <true/false>`` If true, each time the mod makes the raider team it will have the friendly fire disabled -- this friendly fire option is respected over the server.properties pvp option. If that's false then this will have no effect.

``EXTRA_BOSS_CRATES <true/false>`` This determines if the boss will drop only ONE crate on boss kill, or one for each player in the raid. _(I personally recommend false. As it's ONE boss getting killed. But it's your server, so configure it for what is fun for your play group)_
